version: "3.8"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_USER=root
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test:
        [
          "CMD",
          "clickhouse-client --user=root --password=root",
          "--query",
          "SELECT 1",
        ]
      interval: 5s
      retries: 5
  clickhouse-init:
    build: ./docker
    container_name: clickhouse-init
    depends_on:
      clickhouse-server:
        condition: service_healthy
    restart: "no"

networks:
  default:
    driver: bridge
volumes:
  clickhouse_data:
