[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "timestats"
version = "0.1.0"
dependencies = ["pandas", "prettytable", "dotenv"]

[tool.setuptools.packages.find]
include = ["timestats"]

[project.scripts]
timestats = "timestats.cli:main"
